# Generated by Django 4.1.1 on 2022-10-30 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='dni',
            field=models.CharField(max_length=15, unique=True, verbose_name='DPI'),
        ),
    ]
